#!/bin/bash
# SPDX-License-Identifier: GPL-2.0
#
# Copyright (c) 2024 - Greg Kroah-Hartman <gregkh@linuxfoundation.org>
#
# cve_search - Search the published CVE records for the specified git id.
#
# If it is found, the CVE id is returned.
# If it is not found, returns an error.
#
# Usage:
#	cve_search [GIT_ID]
#


# don't use unset variables
set -o nounset

# set where the tool was run from,
# the name of our script,
# and the git version of it
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
SCRIPT=${0##*/}

help() {
	echo "${SCRIPT} [GIT_ID]"
	exit 1
}

STRING="${1:-}"
if [[ "${STRING}" == "" ]] ; then
	help
fi

CVE_ROOT="${DIR}/../cve/"
PUBLISHED_DIR="${CVE_ROOT}published/"

# make sure we haven't allocated a CVE already for this id
found=$(grep -r -l "${STRING}" "${CVE_ROOT}"/published/ "${CVE_ROOT}"/rejected/ | grep "sha1")
if [[ "${found}" == "" ]]; then
	echo "${STRING} not found in any CVE record, sorry."
	exit 1
fi

cve=$(basename "${found}" | cut -f 1 -d '.')

echo "${cve} is assigned to git id ${STRING}"
exit
