name: kernel-security-vulns sync

on:
  schedule:
    - cron: "0 8 * * *"
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
         include:
           - branch: master
             remote: https://git.kernel.org/pub/scm/linux/security/vulns.git
             remote_branch: master

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      BRANCH: ${{ matrix.branch }}
      REMOTE: ${{ matrix.remote }}
      REMOTE_BRANCH: ${{ matrix.remote_branch }}

    steps:
      - name: Install git
        run: sudo apt-get install -y git

      - name: Check out repository
        uses: actions/checkout@v4
        with:
          ref: ${{ env.BRANCH }}
          path: ${{ env.BRANCH }}

      - name: Sync kernel-security-vulns
        working-directory: ./${{ env.BRANCH }}
        run: |
          set -xeuf -o pipefail

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git remote add upstream ${REMOTE}
          git fetch upstream --tags --quiet
          git rebase upstream/${REMOTE_BRANCH}
          git push origin --follow-tags
